# Local equivalents of the GitHub Actions workflows.
# Each workflow has exactly one make target; the workflows stay independent and
# call the underlying scripts directly so CI never depends on make.
#
#   make site      -> .github/workflows/build.yml
#   make medium    -> .github/workflows/fetch_medium.yml
#   make quality   -> .github/workflows/quality.yml

.DEFAULT_GOAL := help
.PHONY: help install site validate build medium quality serve check clean

PYTHON          ?= python3
PORT            ?= 8899
MEDIUM_USERNAME ?= vjmourya
MEDIUM_OUT      := assets/medium_posts.json

# ---------------------------------------------------------------- workflows --

## site: validate data and rebuild every page (mirrors build.yml)
site: validate build

## medium: refresh Medium posts (mirrors fetch_medium.yml)
medium:
	@echo "==> Fetching Medium posts for @$(MEDIUM_USERNAME)"
	@MEDIUM_USERNAME=$(MEDIUM_USERNAME) $(PYTHON) tools/fetch_medium.py $(MEDIUM_OUT)

## quality: HTML validation and link checking (mirrors quality.yml)
quality:
	@echo "==> Validating HTML"
	@npx --yes html-validate@9 --config .htmlvalidate.json '*.html'
	@echo "==> Checking links"
	@if command -v lychee >/dev/null 2>&1; then \
		lychee --offline --no-progress --exclude-mail './**/*.html'; \
	else \
		echo "    lychee not installed - skipping link check (CI still runs it)"; \
	fi

# ------------------------------------------------------------------- pieces --

## validate: check data/*.yaml only
validate:
	@$(PYTHON) tools/validate.py

## build: render pages and JSON assets without validating first
build:
	@$(PYTHON) tools/build.py

# --------------------------------------------------------------- local only --

## serve: build, then preview locally (override with PORT=1234)
serve: site
	@echo "==> Serving on http://localhost:$(PORT)  (Ctrl-C to stop)"
	@$(PYTHON) -m http.server $(PORT)

## check: everything CI would run before a push
check: site quality

## install: install Python and Node dependencies
install:
	@$(PYTHON) -m pip install --upgrade PyYAML Jinja2 feedparser
	@npx --yes html-validate@9 --version >/dev/null

## clean: remove generated JSON assets (HTML is regenerated by `make site`)
clean:
	@rm -f assets/badge_certifications.json
	@echo "Removed generated JSON assets. Run 'make site' to rebuild."

## help: list available targets
help:
	@echo "Portfolio targets:"
	@echo
	@grep -E '^## [a-z]+:' $(MAKEFILE_LIST) \
		| sed -e 's/^## /  /' -e 's/:/|/' \
		| awk -F'|' '{ printf "  \033[36m%-10s\033[0m %s\n", $$1, $$2 }'
	@echo
	@echo "Workflow parity:  site -> build.yml   medium -> fetch_medium.yml   quality -> quality.yml"
